import type { Metadata } from "next";
import React from "react";
import "globals";
export const metadata: Metadata = {
  title: "hw7",
  description: "Generated by lldan",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
